import { useEffect, useMemo, useState } from 'react';
import { LineChart, Line, ResponsiveContainer, ReferenceLine, XAxis, YAxis, Tooltip } from 'recharts';
import ClaimBadge from '../components/ClaimBadge';
import PanelCard from '../components/PanelCard';

const patterns = ['0','+','⌘','◇','T','□','✕','⚓'];
const names = ['Dig-0','Cross','Check','Diam','T-Bar','Frame','Diag','Anchor'];
function overlap(p, noise, bdh) { const c=8.84; const value=bdh ? (p<=c?100-p*.4-noise*.15:97-(p-c)*1.6-noise*.25) : (p<=c?100-p*1.8-noise*.4:100-c*2-(p-c)*5.8-noise*.6); return Math.max(bdh?68:12, Math.min(100, Math.round(value*10)/10)); }
function Slider({label,value,min,max,onChange,color='cyan'}) { return <label className="slider"><span>{label}</span><b className={color}>{value}{label.includes('Noise')?'%':''}</b><input type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)} /></label>; }
export default function DemoPage() {
 const [count,setCount]=useState(8), [noise,setNoise]=useState(24), [bdh,setBdh]=useState(true), [pattern,setPattern]=useState(0), [trace,setTrace]=useState(true), [playing,setPlaying]=useState(false);
 const fidelity=useMemo(()=>overlap(count,noise,bdh),[count,noise,bdh]);
 useEffect(()=>{ if(!playing) return; const id=setInterval(()=>{setCount(p=>p>=24?1:p+1);setPattern(p=>(p+1)%8)},420); return ()=>clearInterval(id); },[playing]);
 const chart=useMemo(()=>Array.from({length:24},(_,i)=>({p:i+1,classical:overlap(i+1,noise,false),bdh:overlap(i+1,noise,true)})),[noise]);
 const tone=fidelity>85?'green':fidelity>50?'amber':'red';
 return <><ClaimBadge /><div className="workbench">
  <PanelCard title="Attractor Library" icon="▦"><div className="panel-meta">ACTIVE TARGET: PAT-{pattern} ({names[pattern]}) <em>ORTHOGONALITY: 0.88</em></div><div className="pattern-grid">{patterns.map((glyph,i)=><button key={glyph} onClick={()=>setPattern(i)} className={pattern===i?'selected':''}><strong>{glyph}</strong><small>PAT-{i}</small></button>)}</div><div className="inset">Synaptic Density: <b>100% Fully Connected</b><hr/>Weight Tensor: 64×64 <em>4,096 SYNAPSES</em></div><div className="button-row"><button onClick={()=>setCount(c=>Math.min(24,c+1))}>⊕ + Orthogonal</button><button onClick={()=>setNoise(Math.floor(Math.random()*45)+5)}>⚄ Randomize</button></div><button className="wide ghost" onClick={()=>setCount(1)}>⌫ Clear Library</button></PanelCard>
  <PanelCard title="Experiment Tuning & Gating" icon="☷" className="controls"><div className="mode"><button onClick={()=>setBdh(false)} className={!bdh?'active classical':''}>Classical Hebbian</button><button onClick={()=>setBdh(true)} className={bdh?'active':''}>ϟ BDH-Style Sparse</button></div><p className="caption"><b>{bdh?'BDH Sparse Coding:':'Classical Dense Hebbian:'}</b> {bdh?'Suppresses parasitic crosstalk using sparse dynamic gating and soft thresholds.':'Full outer-product sum is vulnerable to saturation after 0.138N.'}</p><Slider label="Stored Patterns (P)" value={count} min={1} max={24} onChange={setCount}/><Slider label="Input Noise" value={noise} min={0} max={60} onChange={setNoise} color="amber"/><label className="check"><input type="checkbox" checked={trace} onChange={e=>setTrace(e.target.checked)}/> Trace the Math</label>{trace&&<div className="formula">ΔWᵢⱼ = η · sᵢ · sⱼ &nbsp; | &nbsp; α = {(count/64).toFixed(3)}</div>}<div className="button-row"><button onClick={()=>setPattern(p=>(p+1)%8)}>→ Next</button><button className="prove" onClick={()=>setPlaying(v=>!v)}>{playing?'■ Stop':'▶ Prove It'}</button></div></PanelCard>
  <PanelCard title="Associative Readout" icon="◉"><div className="readout"><div><span className="glyph noisy">{patterns[pattern]}</span><small>NOISY INPUT</small></div><b>→</b><div><span className={`glyph ${tone}`}>{fidelity>40?patterns[pattern]:'?'}</span><small>RETRIEVED</small></div><b>→</b><div><span className="glyph green">{patterns[pattern]}</span><small>GROUND TRUTH</small></div></div><div className="metric"><small>OVERLAP / RETRIEVAL FIDELITY</small><strong className={tone}>{fidelity.toFixed(1)}%</strong><div><i className={tone} style={{width:`${fidelity}%`}}/></div></div><div className="inset">Energy descent converged in 7 iterations<br/><em>Attractor basin: {bdh?'ROBUST':'FRAGILE'}</em></div></PanelCard>
 </div><section className="chart-panel"><h2>Theoretical Capacity Basin: Retrieval Fidelity vs Pattern Count (P)</h2><ResponsiveContainer width="100%" height={260}><LineChart data={chart}><XAxis dataKey="p" stroke="#87929a"/><YAxis domain={[0,100]} stroke="#87929a"/><Tooltip contentStyle={{background:'#171f33',border:'1px solid #3e484f'}}/><ReferenceLine x={count} stroke="#38bdf8"/><Line dataKey="classical" stroke="#ffb95f" strokeWidth={2} dot={false}/><Line dataKey="bdh" stroke="#38bdf8" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer><div className="legend"><span>━ Classical Hebbian</span><b>━ BDH sparse manifold</b></div></section><section className="failure"><h2>Pathological Attractor States (Failure Gallery)</h2>{['Chimeric Fusion','Spin Glass Collapse','Synaptic Saturation'].map((x,i)=><article key={x}><span>{['◩','✣','◉'][i]}</span><h3>{x}</h3><p>Classical dense storage induces a degraded, unstable basin at high memory load.</p><button onClick={()=>{setBdh(false);setCount(18)}}>Load state →</button></article>)}</section></>;
}
