export const CONFIG = {
  PATTERN_DIM: 64, GRID_SIZE: 8,
  MAX_PATTERNS: 20, MIN_PATTERNS: 1,
  NOISE_MIN: 0, NOISE_MAX: 100,
  MAX_ITERATIONS: 10, CONVERGENCE_EPSILON: 0,
  PASS_THRESHOLD: 90, SPARSITY_PCT: 30,
  DECAY_DEFAULT: 1.0,
};
